apiVersion: apps/v1
kind: Deployment
metadata:
  name: publication-service
  labels:
    app: publication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publication-service
  template:
    metadata:
      labels:
        app: publication-service
    spec:
      containers:
        - name: publication-service
          image: youssef07/publication-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: publication-service-svc
spec:
  ports:
    - port: 80
      targetPort: 8082
  selector:
    app: publication-service

